# Generated by Django 2.2.1 on 2019-06-20 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('data', models.CharField(default=datetime.datetime.now, max_length=30)),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='immagini_database')),
            ],
            options={
                'verbose_name_plural': 'ARTICOLI BLOG',
            },
        ),
    ]
