# Generated by Django 2.2.1 on 2019-07-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='autore',
            field=models.TextField(blank=True, null=True),
        ),
    ]
