# Generated by Django 2.2.1 on 2019-07-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_blogpost_autore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='autore',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
