# Generated by Django 2.2.1 on 2019-07-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_auto_20190709_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='data',
            field=models.DateField(max_length=30),
        ),
    ]
