# Generated by Django 2.2.1 on 2019-07-10 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_auto_20190710_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='data',
            field=models.DateField(default=django.utils.timezone.now, max_length=30),
        ),
    ]
